server:
  port: 9100
spring:
  application:
    name: ConvertCurrency

#CurrencyConversionFactor:
#  ribbon:
#    listOfServers: http://localhost:9000, http://localhost:9001 

eureka:
   client:
     server-url:
       default-zone: http://localhost:8761/eureka  