server:
  port: 8080
spring:
  application:
    name: ConvertCurrency
#CurrencyConversionFactor:
#  ribbon:
#    listOfServers: http://localhost:9000, http://localhost:9001 
eureka:
     instance:
       prefer-ip-address: true
     client:
       proxy-host: localhost
       register-with-eureka: true
       fetch-registry: true
       service-url:
          default-zone: http://localhost:8761/eureka 