server:
  port: 8080
spring:
  application:
    name: ConvertCurrency
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0  
  zipkin:
    enabled: true
    base-url: http://34.71.225.108:9411/
#CurrencyConversionFactor:
#  ribbon:
#    listOfServers: http://localhost:9000, http://localhost:9001 
eureka:
     client:
       register-with-eureka: true
       fetch-registry: true
       service-url:
          defaultZone: http://104.155.182.25:8761/eureka/