server:
  port: 9080
spring:
  application:
    name: CurrencyConversionFactor
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:conversionFactorDB
    username: sa
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0  
  zipkin:
    enabled: true
    base-url: http://34.71.225.108:9411/
#    base-url: http://192.168.99.100:9411/
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
       defaultZone: http://104.155.182.25:8761/eureka/  