server:
  port: 9080
spring:
  application:
    name: CurrencyConversionFactor
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:conversionFactorDB
    username: sa
    
eureka:
     instance:
       prefer-ip-address: true
     client:
       proxy-host: localhost
       register-with-eureka: true
       fetch-registry: true
       service-url:
          default-zone: http://localhost:8761/eureka
          