server:
  port: 9000
spring:
  application:
    name: CurrencyConversionFactor
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:conversionFactorDB
    username: sa
    
eureka:
   client:
     server-url:
       default-zone: http://localhost:8761/eureka