spring:
  application:
    name: EurekaNamingServer  
server:
  port: 8761    
eureka:
  instance:
    hostname: 104.155.182.25
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/