spring:
  application:
    name: EurekaNamingServer    
server:
  port: 8761    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
    