server:
  port: 9999
spring:
  security:
    user:
      name: ram
      password: password
      roles: ADMIN, USER
security:
  oauth2:
    client:
      client-id: cart
      client-secret: cartpassword
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token, authorization_code, password, client_credentials
      scope: READ, WRITE, DELETE
    authorization:
      check-token-access: permitAll
      