server:
  port: 9300
spring:
  application:
    name: cart-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:CartDB
    username: sa
    password: 
